import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from '@/layout/Header/Header';
import Footer from '@/layout/Footer/Footer';
import { ModalContextProvider } from '@/context/modal.context';
import MobileButton from '@/components/MobileButton/MobileButton';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Клининг Профи. Услуги клининга, химчистки',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <ModalContextProvider>
        <body className={montserrat.className}>
          <Header />
          {children}
          <Footer />
          <MobileButton />
        </body>
      </ModalContextProvider>
    </html>
  );
}
